use std::env;
use std::fs::{self, File};
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    emit_md5_env(
        "U2_JAR_MD5",
        Path::new("assets/u2.jar"),
        Some("u2.jar file is missing"),
    );
    emit_md5_env(
        "UIAUTOMATOR_APK_MD5",
        Path::new("assets/app-uiautomator.apk"),
        Some("app-uiautomator.apk file is missing"),
    );
    emit_md5_env(
        "UIAUTOMATOR_TEST_APK_MD5",
        Path::new("assets/app-uiautomator-test.apk"),
        Some("app-uiautomator-test.apk file is missing"),
    );
    // Backward compatibility for examples/tools that still read a single ATX MD5.
    emit_md5_env(
        "ATX_AGENT_MD5",
        Path::new("assets/atx-agent"),
        Some("atx-agent file is missing"),
    );

    generate_atx_agent_assets_module();
}

fn emit_md5_env(var_name: &str, path: &Path, warning: Option<&str>) {
    if path.exists() {
        let bytes = fs::read(path).unwrap_or_else(|_| panic!("failed to read {}", path.display()));
        let md5_hash = format!("{:x}", md5::compute(&bytes));
        println!("cargo:rustc-env={var_name}={md5_hash}");
    } else {
        println!("cargo:rustc-env={var_name}=placeholder");
        if let Some(msg) = warning {
            println!("cargo:warning={msg}");
        }
    }
    println!("cargo:rerun-if-changed={}", path.display());
}

fn generate_atx_agent_assets_module() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is not set"));
    let out_file = out_dir.join("atx_agent_assets.rs");
    let mut file = File::create(&out_file).expect("failed to create atx_agent_assets.rs");

    writeln!(file, "// Auto-generated by build.rs. Do not edit manually.")
        .expect("failed to write header");

    emit_atx_agent_const(
        &mut file,
        "ATX_AGENT_LEGACY",
        "ATX_AGENT_MD5_LEGACY",
        Path::new("assets/atx-agent"),
    );
    emit_atx_agent_const(
        &mut file,
        "ATX_AGENT_ARMV7",
        "ATX_AGENT_MD5_ARMV7",
        Path::new("assets/atx-agent-armv7"),
    );
    emit_atx_agent_const(
        &mut file,
        "ATX_AGENT_ARM64",
        "ATX_AGENT_MD5_ARM64",
        Path::new("assets/atx-agent-arm64"),
    );
    emit_atx_agent_const(
        &mut file,
        "ATX_AGENT_AMD64",
        "ATX_AGENT_MD5_AMD64",
        Path::new("assets/atx-agent-amd64"),
    );
    emit_atx_agent_const(
        &mut file,
        "ATX_AGENT_386",
        "ATX_AGENT_MD5_386",
        Path::new("assets/atx-agent-386"),
    );
}

fn emit_atx_agent_const(file: &mut File, const_name: &str, md5_env_name: &str, path: &Path) {
    if path.exists() {
        let abs_path = fs::canonicalize(path)
            .unwrap_or_else(|_| panic!("failed to canonicalize {}", path.display()));
        let bytes = fs::read(path).unwrap_or_else(|_| panic!("failed to read {}", path.display()));
        let md5_hash = format!("{:x}", md5::compute(&bytes));
        println!("cargo:rustc-env={md5_env_name}={md5_hash}");
        writeln!(
            file,
            "pub const {const_name}: &[u8] = include_bytes!(r#\"{}\"#);",
            abs_path.display()
        )
        .expect("failed to write const bytes");
    } else {
        println!("cargo:rustc-env={md5_env_name}=placeholder");
        writeln!(file, "pub const {const_name}: &[u8] = &[];")
            .expect("failed to write empty const");
    }

    writeln!(
        file,
        "pub const {const_name}_MD5: &str = env!(\"{md5_env_name}\");"
    )
    .expect("failed to write const md5");
    println!("cargo:rerun-if-changed={}", path.display());
}
